pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('spring-user-management-master') {
                    sh './mvnw clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('spring-user-management-master') {
                    sh './mvnw test'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('spring-user-management-master') {
                    sh 'docker build -t authorization-app .'
                }
            }
        }
    }
}